Repository blooming-inpeak/inpeak-back, pull requests merged in 2025-08, with the labels that each got.

#16 ecr을 통한 cd 작업 설정합니다
  .gitignore
  inpeak/.github/workflows/deploy-ecr.yml
  inpeak/Dockerfile
Labels: chore

#17 ECR을 통한 CI/CD 작업이 정상적으로 동작하는지 테스트
  inpeak/src/main/java/com/blooming/inpeak/answer/controller/AnswerController.java
Labels: chore

#20 chore: ECR cicd를 위한 주석 추가 - v6 (#2)
  inpeak/src/main/java/com/blooming/inpeak/answer/controller/AnswerControllerV2.java
Labels: chore

#23 chore: ECR cicd를 위한 deploy yml 변경 - v9 (#2)
  .github/workflows/deploy-ecr.yml
Labels: chore

#25 chore: ECR cicd - v11 (#2)
  inpeak/Dockerfile
Labels: chore

#26 chore: ECR cicd - v12 (#2)
  inpeak/src/main/java/com/blooming/inpeak/answer/controller/AnswerControllerV2.java
Labels: chore

#30 CodeDeploy PATH 환경변수 손상 문제 해결합니다
  .gitignore
  inpeak/scripts/install_dependencies.sh
Labels: fix

#34 인터뷰 횟수 제한을 일시적으로 해제합니다
  inpeak/src/main/java/com/blooming/inpeak/interview/service/InterviewService.java
  inpeak/src/test/java/com/blooming/inpeak/interview/service/InterviewServiceTest.java
  inpeak/src/test/java/com/blooming/inpeak/interview/service/InterviewStartServiceTest.java
Labels: feat
